---

owner: itc-herden-ops
repo: upptime

sites:
  - name: INT1
    url: $INT1
    headers:
      - "Authorization: Basic $BASICAUTH"
  - name: INT2
    url: $INT2
    headers:
      - "Authorization: Basic $BASICAUTH"
  - name: PROD
    url: $PROD
    headers:
      - "Authorization: Basic $BASICAUTH"

assignees:
  - itc-herden-ops

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/itc-herden-ops/upptime

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
